# Generated by Django 4.2.1 on 2023-05-22 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favourites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planetfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moviefavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='planetfavourite',
            constraint=models.UniqueConstraint(fields=('user', 'swapi_url'), name='unique_user_planet'),
        ),
        migrations.AddConstraint(
            model_name='moviefavourite',
            constraint=models.UniqueConstraint(fields=('user', 'swapi_url'), name='unique_user_movie'),
        ),
    ]
